# Generated by Django 3.1.2 on 2021-05-10 00:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_profile_profile_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_instance_id', models.CharField(default='PPI-8VXE91SP4NC0A9LK', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=200)),
                ('slots', models.IntegerField(default=0)),
                ('value_bought', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('percentage_perf', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('all_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('entry_starts', models.DateField(blank=True, max_length=100, null=True)),
                ('entry_ends', models.DateField(blank=True, max_length=100, null=True)),
                ('run_starts', models.DateField(blank=True, max_length=100, null=True)),
                ('run_ends', models.DateField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PoolOfferings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PoolPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('maturity_desc', models.CharField(max_length=200)),
                ('period_hrs', models.IntegerField()),
                ('period_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserPoolSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnx_code', models.CharField(default='JCBHUJUXKXT', max_length=200)),
                ('slots_taken', models.IntegerField(default=1)),
                ('slots_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='pipminds/pools_contracts')),
                ('pool_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pool_instance', to='pools.poolinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pool_slots', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserOfferingsPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_code', models.CharField(default='GMG0URV9', max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offerings', models.ManyToManyField(related_name='users_offering_purchases', to='pools.PoolOfferings')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PoolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unique_pool_type_id', models.CharField(default='PPT-FYN5WG4V', max_length=200)),
                ('min_percentage_promise', models.IntegerField(default=1)),
                ('max_percentage_promise', models.IntegerField(default=1)),
                ('amount_per_slot', models.DecimalField(decimal_places=2, max_digits=19)),
                ('can_spin_new', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('active_period_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pool_period_active_window', to='pools.poolperiod')),
                ('entry_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pool_period_entry_window', to='pools.poolperiod')),
            ],
        ),
        migrations.CreateModel(
            name='PoolsWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='poolinstance',
            name='pool_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.pooltype'),
        ),
    ]
