# Generated by Django 3.1.2 on 2020-10-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_membership_subscription_usermembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='paystack_unique_user_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
