# Generated by Django 3.1.2 on 2020-10-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermembership_paystack_unique_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='investment_kyc_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
