# Generated by Django 3.1.2 on 2020-10-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_investment_kyc_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='investement_verified',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=200),
        ),
    ]
