# Generated by Django 3.1.2 on 2020-10-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userreferrals'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreferrals',
            unique_together={('sponsor', 'downline')},
        ),
    ]
