# Generated by Django 3.1.2 on 2021-01-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201224_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pioneer_ppp_reg_expires',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
