# Generated by Django 3.1.2 on 2021-01-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_pioneer_ppp_reg_expires'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImportDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, null=True, upload_to='documents/admin_import')),
            ],
        ),
    ]
