# Generated by Django 3.1.2 on 2021-01-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210107_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cip_pioneer_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='remit_inv_funds_to_wallet',
            field=models.BooleanField(default=False),
        ),
    ]
