# Generated by Django 3.1.2 on 2021-04-25 06:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0023_subscriptioninstance_contract_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_instance_id', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=200)),
                ('slots', models.IntegerField(default=1)),
                ('percentage_perf', models.DecimalField(decimal_places=2, max_digits=19)),
                ('all_earnings', models.DecimalField(decimal_places=2, max_digits=19)),
                ('active', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PoolOfferings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PoolPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('maturity_desc', models.CharField(max_length=200)),
                ('period_hrs', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserPoolSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnx_code', models.CharField(max_length=200)),
                ('slots_taken', models.IntegerField(default=1)),
                ('slots_value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pool_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pool_instance', to='pools.poolinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pool_slots', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PoolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unique_pool_type_id', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('max_slots', models.IntegerField()),
                ('amount_per_slot', models.DecimalField(decimal_places=2, max_digits=19)),
                ('can_spin_new', models.BooleanField(default=False)),
                ('offerings', models.ManyToManyField(blank=True, null=True, to='pools.PoolOfferings')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pools.poolperiod')),
            ],
        ),
        migrations.AddField(
            model_name='poolinstance',
            name='pool_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.pooltype'),
        ),
    ]
