# Generated by Django 3.1.2 on 2021-04-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_auto_20210425_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooltype',
            name='offerings',
            field=models.ManyToManyField(to='pools.PoolOfferings'),
        ),
    ]
