# Generated by Django 3.1.2 on 2021-04-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_auto_20210427_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoolslots',
            name='slots_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
