# Generated by Django 3.1.2 on 2021-05-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_auto_20210427_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pooltype',
            name='max_slots',
        ),
    ]
