# Generated by Django 3.1.2 on 2021-05-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0008_auto_20210504_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolperiod',
            name='period_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poolinstance',
            name='unique_instance_id',
            field=models.CharField(default='PPT-4QUEPFUWSBR', max_length=200),
        ),
        migrations.AlterField(
            model_name='pooltype',
            name='unique_pool_type_id',
            field=models.CharField(default='PPT-0HB6UGPQ34F', max_length=200),
        ),
    ]
