# Generated by Django 3.1.2 on 2021-05-05 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0009_auto_20210504_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pooltype',
            name='offerings',
        ),
        migrations.AddField(
            model_name='userpoolslots',
            name='offerings',
            field=models.ManyToManyField(to='pools.PoolOfferings'),
        ),
        migrations.AlterField(
            model_name='poolinstance',
            name='unique_instance_id',
            field=models.CharField(default='PPT-GOYBQQLHF5G', max_length=200),
        ),
        migrations.AlterField(
            model_name='pooltype',
            name='unique_pool_type_id',
            field=models.CharField(default='PPT-3VAA0P6C44T', max_length=200),
        ),
        migrations.CreateModel(
            name='UserOfferingsPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offerings', models.ManyToManyField(related_name='users_offering_purchases', to='pools.PoolOfferings')),
            ],
        ),
    ]
