# Generated by Django 3.1.2 on 2021-05-05 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210504_1927'),
        ('pools', '0010_auto_20210505_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='userofferingspurchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='poolinstance',
            name='unique_instance_id',
            field=models.CharField(default='PPT-VXHTC741SN0', max_length=200),
        ),
        migrations.AlterField(
            model_name='pooltype',
            name='unique_pool_type_id',
            field=models.CharField(default='PPT-VH8C9CMZFR6', max_length=200),
        ),
    ]
