# Generated by Django 3.1.2 on 2021-05-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0011_auto_20210505_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userofferingspurchase',
            name='txn_code',
            field=models.CharField(default='OWBSRFGID1C', max_length=200),
        ),
        migrations.AlterField(
            model_name='poolinstance',
            name='unique_instance_id',
            field=models.CharField(default='PPI-JE0Y18ALCUI1V2BR', max_length=200),
        ),
        migrations.AlterField(
            model_name='pooltype',
            name='unique_pool_type_id',
            field=models.CharField(default='PPT-A299TNIZ', max_length=200),
        ),
        migrations.AlterField(
            model_name='userpoolslots',
            name='tnx_code',
            field=models.CharField(default='IPOLU93YYRF', max_length=200),
        ),
    ]
