# Generated by Django 3.1.2 on 2021-05-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0012_auto_20210505_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolofferings',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poolinstance',
            name='unique_instance_id',
            field=models.CharField(default='PPI-R638SMW5ZKPWDHHM', max_length=200),
        ),
        migrations.AlterField(
            model_name='pooltype',
            name='unique_pool_type_id',
            field=models.CharField(default='PPT-EPHKWZRI', max_length=200),
        ),
        migrations.AlterField(
            model_name='userofferingspurchase',
            name='txn_code',
            field=models.CharField(default='KPN8G22CR6P', max_length=200),
        ),
        migrations.AlterField(
            model_name='userpoolslots',
            name='tnx_code',
            field=models.CharField(default='X07VMHO77ZB', max_length=200),
        ),
    ]
