# Generated by Django 3.1.2 on 2021-05-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0013_auto_20210505_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolinstance',
            name='unique_instance_id',
            field=models.CharField(default='PPI-GS9RIPRWVAL1KURA', max_length=200),
        ),
        migrations.AlterField(
            model_name='pooltype',
            name='unique_pool_type_id',
            field=models.CharField(default='PPT-IB0BK484', max_length=200),
        ),
        migrations.AlterField(
            model_name='userofferingspurchase',
            name='txn_code',
            field=models.CharField(default='ONIVGOF7EFN', max_length=200),
        ),
        migrations.AlterField(
            model_name='userpoolslots',
            name='tnx_code',
            field=models.CharField(default='LANQI7WPBNS', max_length=200),
        ),
    ]
