# Generated by Django 3.1.2 on 2021-05-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0014_auto_20210505_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpoolslots',
            name='offerings',
        ),
        migrations.AlterField(
            model_name='poolinstance',
            name='unique_instance_id',
            field=models.CharField(default='PPI-JTOK0XEVDK8FKX3A', max_length=200),
        ),
        migrations.AlterField(
            model_name='pooltype',
            name='unique_pool_type_id',
            field=models.CharField(default='PPT-1HHEOWQY', max_length=200),
        ),
        migrations.AlterField(
            model_name='userofferingspurchase',
            name='txn_code',
            field=models.CharField(default='LTTBGIUZCWE', max_length=200),
        ),
        migrations.AlterField(
            model_name='userpoolslots',
            name='tnx_code',
            field=models.CharField(default='ZZS3WNA5LJK', max_length=200),
        ),
    ]
