# Generated by Django 3.1.2 on 2021-05-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0015_auto_20210505_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolinstance',
            name='unique_instance_id',
            field=models.CharField(default='PPI-1G3AI5150ZBLWAT4', max_length=200),
        ),
        migrations.AlterField(
            model_name='pooltype',
            name='unique_pool_type_id',
            field=models.CharField(default='PPT-CMBEHLOI', max_length=200),
        ),
        migrations.AlterField(
            model_name='userofferingspurchase',
            name='txn_code',
            field=models.CharField(default='TFWTMXWN', max_length=200),
        ),
        migrations.AlterField(
            model_name='userpoolslots',
            name='tnx_code',
            field=models.CharField(default='IN09F4IVVHR', max_length=200),
        ),
    ]
