# Generated by Django 3.1.2 on 2021-05-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0016_auto_20210505_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolinstance',
            name='unique_instance_id',
            field=models.CharField(default='PPI-KVNVD54YE1YWN84I', max_length=200),
        ),
        migrations.AlterField(
            model_name='pooltype',
            name='unique_pool_type_id',
            field=models.CharField(default='PPT-9XKQ5ZHQ', max_length=200),
        ),
        migrations.AlterField(
            model_name='userofferingspurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='userofferingspurchase',
            name='txn_code',
            field=models.CharField(default='9UAELQ9D', max_length=200),
        ),
        migrations.AlterField(
            model_name='userpoolslots',
            name='tnx_code',
            field=models.CharField(default='PPSORW2P5R0', max_length=200),
        ),
    ]
