# Generated by Django 3.1.2 on 2021-05-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0017_auto_20210505_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolinstance',
            name='all_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='poolinstance',
            name='percentage_perf',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='poolinstance',
            name='unique_instance_id',
            field=models.CharField(default='PPI-RCLWBKP0SYY2YI26', max_length=200),
        ),
        migrations.AlterField(
            model_name='poolinstance',
            name='value_bought',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='poolofferings',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='pooltype',
            name='unique_pool_type_id',
            field=models.CharField(default='PPT-8TASZJI9', max_length=200),
        ),
        migrations.AlterField(
            model_name='userofferingspurchase',
            name='txn_code',
            field=models.CharField(default='KAOTMDY0', max_length=200),
        ),
        migrations.AlterField(
            model_name='userpoolslots',
            name='slots_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='userpoolslots',
            name='tnx_code',
            field=models.CharField(default='TDBDS09E3BR', max_length=200),
        ),
    ]
