# Generated by Django 3.1.2 on 2021-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0018_auto_20210505_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoolslots',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='pipminds/pools_contracts'),
        ),
        migrations.AlterField(
            model_name='poolinstance',
            name='unique_instance_id',
            field=models.CharField(default='PPI-7KBIQNRD6FBAZ2FY', max_length=200),
        ),
        migrations.AlterField(
            model_name='pooltype',
            name='unique_pool_type_id',
            field=models.CharField(default='PPT-DBTA7L7E', max_length=200),
        ),
        migrations.AlterField(
            model_name='userofferingspurchase',
            name='txn_code',
            field=models.CharField(default='ID7H5AIY', max_length=200),
        ),
        migrations.AlterField(
            model_name='userpoolslots',
            name='tnx_code',
            field=models.CharField(default='4IS8EIL4RVY', max_length=200),
        ),
    ]
