# Generated by Django 3.1.2 on 2020-12-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201230_1449'),
        ('investment', '0004_auto_20201221_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinvestment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_investments', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='userinvestmentearnings',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_investment_earnings', to='investment.userinvestment'),
        ),
    ]
