# Generated by Django 3.1.2 on 2021-01-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_auto_20201230_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='cip_pioneer',
            field=models.BooleanField(default=False),
        ),
    ]
