# Generated by Django 3.1.2 on 2021-04-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_capitalpaybacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='can_top_up',
            field=models.BooleanField(default=True),
        ),
    ]
