# Generated by Django 3.1.2 on 2020-10-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20201014_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainwallet',
            name='overall_balance',
        ),
    ]
