# Generated by Django 3.1.2 on 2020-10-20 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentwallet',
            name='main_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investmentwallet', to='wallet.mainwallet'),
        ),
        migrations.AlterField(
            model_name='referralwallet',
            name='main_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referralwallet', to='wallet.mainwallet'),
        ),
    ]
