# Generated by Django 3.1.2 on 2020-10-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20201021_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='last_withrawal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
