# Generated by Django 3.1.2 on 2020-10-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20201021_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='mainwallet',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='mainwallet',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='referralwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
