# Generated by Django 3.1.2 on 2020-10-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201028_1614'),
        ('wallet', '0009_userreferralearnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentwallet',
            name='main_wallet',
        ),
        migrations.RemoveField(
            model_name='referralwallet',
            name='main_wallet',
        ),
        migrations.AddField(
            model_name='investmentwallet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='referralwallet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
