# Generated by Django 3.1.2 on 2020-10-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_auto_20201029_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='wallet',
            field=models.CharField(choices=[('main', 'Main Wallet'), ('referrals', 'Referral Wallet'), ('investments', 'Investment Wallet')], default='main', max_length=200),
        ),
    ]
