# Generated by Django 3.1.2 on 2020-12-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment_earnings', 'Investment Earnings'), ('referral_earnings', 'Referral Earnings')], default='deposit', max_length=200),
        ),
    ]
