# Generated by Django 3.1.2 on 2021-01-24 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
