# Generated by Django 3.1.2 on 2021-01-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_payments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
