# Generated by Django 3.1.2 on 2021-03-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_auto_20210303_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='deposit/proof_of_payment'),
        ),
    ]
