# Generated by Django 3.1.2 on 2021-03-12 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_auto_20210311_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_sol', models.CharField(blank=True, max_length=500, null=True)),
                ('the_trans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction')),
            ],
        ),
    ]
