# Generated by Django 3.1.2 on 2021-03-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0023_webhookbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookbackup',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
