# Generated by Django 3.1.2 on 2021-05-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0026_auto_20210504_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoolsWallet',
        ),
    ]
