# Generated by Django 3.1.2 on 2020-12-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_supporttickets_usernotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ppp_started',
            field=models.BooleanField(default=False),
        ),
    ]
