# Generated by Django 3.1.2 on 2021-01-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201230_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pioneer_ppp_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='pioneer_ppp_reg_expires',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
