# Generated by Django 3.1.2 on 2021-01-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210107_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImportDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, null=True, upload_to='pipminds/import_documents/admin_import')),
            ],
        ),
    ]
