# Generated by Django 3.1.2 on 2021-04-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210404_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninstance',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='pipminds/ppp_contracts'),
        ),
    ]
