# Generated by Django 3.1.2 on 2021-05-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_subscriptioninstance_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_phase',
            field=models.CharField(choices=[('live_prod', 'Live Prod'), ('phase_one', 'Phase One'), ('phase_two', 'Phase Two'), ('beta', 'Beta')], default='live_prod', max_length=200),
        ),
    ]
