# Generated by Django 3.1.2 on 2021-02-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20210130_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='destination',
            field=models.CharField(choices=[('investment_wallet', 'Investment Wallet'), ('referral_wallet', 'Referral Wallet'), ('bank_account', 'Bank Account')], default='bank_account', max_length=200),
        ),
        migrations.AddField(
            model_name='payments',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
