# Generated by Django 3.1.2 on 2021-03-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20210304_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='trans_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='trans_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='trans_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
