# Generated by Django 3.1.2 on 2020-10-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinvestmentearnings',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinvestmentearnings',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
