# Generated by Django 3.1.2 on 2020-10-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_auto_20201014_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
