# Generated by Django 3.1.2 on 2020-10-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_investmentplan_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestment',
            name='maturity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
