# Generated by Django 3.1.2 on 2020-10-28 23:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_auto_20201014_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestmentearnings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userinvestmentearnings',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.userinvestment'),
        ),
    ]
