# Generated by Django 3.1.2 on 2020-10-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_auto_20201029_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentplan',
            name='maturity_period',
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='max_maturity_period',
            field=models.IntegerField(default=270),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='min_maturity_period',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='maturity_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
