# Generated by Django 3.1.2 on 2020-10-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_auto_20201029_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='max_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
