# Generated by Django 3.1.2 on 2020-11-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_auto_20201029_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='next_payout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
