# Generated by Django 3.1.2 on 2020-12-18 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0011_auto_20201218_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentplan',
            old_name='thrid_maturity_period',
            new_name='third_maturity_period',
        ),
    ]
