# Generated by Django 3.1.2 on 2020-12-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_auto_20201218_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='profit_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='profit_paid',
            field=models.IntegerField(default=0),
        ),
    ]
