# Generated by Django 3.1.2 on 2020-12-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_ppp_started'),
        ('investment', '0013_auto_20201220_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_investments', to='users.profile'),
        ),
    ]
