# Generated by Django 3.1.2 on 2020-12-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0014_auto_20201224_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestmentearnings',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_investment_earnings', to='investment.userinvestment'),
        ),
    ]
