# Generated by Django 3.1.2 on 2020-12-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0015_auto_20201224_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
