# Generated by Django 3.1.2 on 2021-02-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0020_userinvestmenttopups'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='pipminds/investment_contracts'),
        ),
        migrations.AddField(
            model_name='userinvestmenttopups',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='pipminds/investment_top_up_contracts'),
        ),
    ]
