# Generated by Django 3.1.2 on 2021-03-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0022_userinvestmentrollovers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='has_been_rolled_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='is_rollover',
            field=models.BooleanField(default=False),
        ),
    ]
