# Generated by Django 3.1.2 on 2021-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0025_capitalpaybacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
    ]
