# Generated by Django 3.1.2 on 2021-04-04 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0026_userinvestment_terminated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvestment',
            name='terminated',
        ),
    ]
