# Generated by Django 3.1.2 on 2021-04-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0028_userinvestment_can_top_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestment',
            name='can_top_up',
            field=models.BooleanField(default=True),
        ),
    ]
